language: python
python:
- 3.8
- 3.7
- 3.6
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: __token__
  password:
    secure: I2QQQVGC+ld8fMaOZRnxJH8seW3UHpDhL8KRx+MRp1PNdHo2fMfFlXcwrcNySSxnzg6DVxwQu6CP286hmSZPsk8JZctCCe2h2RA9s0PuWlYYvC1+tGelT5iyp8JvpF+OsI3rvxKsYd0DX+SWKBSp/HvtekHmcfmctm+H7p4SZxaUxKnJDI5q9TSTZ6nzv3ccm7PXGTQdUxe2J1YMTXWZ0Bn/HuPpsiCqjs+XXW1ws/pLedVLjWidHLCmADoCVKkwBrZ454t6mwHUrcm7GgdpKWxj+61YwQ+z6n+PcOD0c7dkz835udmPFv7YgBWb53QPQQ6A5zOydUA6Tka2YePJ57UE40+AUjDUdmpgGapTzLHu511rCMsF4K6q0NnjCKo7jYUNwyOeBkDqsAKoyBBNaNEWY3HlP6L1YdxDbicauS77DNsVCsaQKllQFzrs5Ybt+IYf7S5vyqm59STMJDIeCY22im+ArsGB+e4awl2d4FvLxgNpiluIubcUI95WWOwFMFY2ep8xnrLrNKuudBFFmlPFFBXOTncy4h7sobvwsLi44PISj7WWN22WVMlBgP4T6vKdF4N9kAOnU9ER5RT6KegYpB8Y/iu8ahFPt3+dstUycpxmGYi128m6MK6rhTZAlgHJbJ63/dBNy/YBb6aQLVw2qtB69cu4pIStdqbL0P8=
  on:
    tags: true
    repo: 34j/ut_course_catalog
    python: 3.8
